name: digital_smart_trolly_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter 
  share_plus: ^10.1.4 
  cached_network_image: ^3.3.0 
  url_launcher: ^6.1.14
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  weather: ^3.0.0   

  # Firebase Core (Required for Firebase Initialization)
  firebase_core: ^3.11.0
  
  # Firebase Authentication (User Login, Signup)
  firebase_auth: ^5.4.2
  
  # Firebase Firestore (Cloud Database)
  cloud_firestore: ^5.6.3
  
  # Firebase Storage (For uploading images/files)
  firebase_storage: ^12.4.2

  # Firebase Messaging (Push Notifications)
  firebase_messaging: ^15.2.2

  # Firebase Analytics (User Behavior Tracking)
  firebase_analytics: ^11.4.2

  # Firebase Crashlytics (Error Monitoring)
  firebase_crashlytics: ^4.3.2

  # Google Sign-In (If needed)
  google_sign_in: ^6.1.6

  # UI Components
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/logo1.png
    - assets/images/Fruits.png
    - assets/images/Meat.png
    - assets/images/Vegetables.png
    - assets/images/Dairy.png
    - assets/images/Snacks.png
    - assets/images/Bakery.png
    - assets/images/Trolley.png
    - assets/images/map_placeholder.png

